version: '3.8'

volumes:
  db-data:

services:
  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: ${WORKDIR}
        CONTAINER_PORT: ${CONTAINER_PORT}
    command: yarn run dev
    volumes:
      - ./frontend:/${WORKDIR}
    ports:
      - "${FRONTEND_PORT}:${CONTAINER_PORT}"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: ${WORKDIR}
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backend:/${WORKDIR}
    ports:
      - "${BACKEND_PORT}:${CONTAINER_PORT}"
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Aisa/Tokyo
    ports:
      - '3306:3306'
